// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HomeController from "./home_controller"
application.register("home", HomeController)

import DisposableToastController from "./disposable_toast_controller"
application.register("disposable-toast", DisposableToastController)

import NewLessonModalController from "./new_lesson_modal_controller"
application.register("new-lesson-modal", NewLessonModalController)

import LatchController from "./latch_controller"
application.register("latch", LatchController)

import DisposableModalController from "./disposable_modal_controller"
application.register("disposable-modal", DisposableModalController)
